spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/app-transporte
    username: postgres
    password: ana301200
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  data:
    redis:
      host: localhost
      port: 6379

  logging:
    level:
      root: DEBUG